---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paulbo1q/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp results.html $DEPLOYPATH
    - /bin/cp style/style.css $DEPLOYPATH
    - /bin/cp images/Darts.png
    - /bin/cp images/fav.png